"""empty message

Revision ID: 67fe8e8fed1f
Revises: b7e4d68f940f
Create Date: 2024-06-07 17:48:29.620580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fe8e8fed1f'
down_revision: Union[str, None] = 'b7e4d68f940f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('ad', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ad', 'ad_category', ['category_id'], ['id'])
    op.drop_column('ad', 'phone')
    op.drop_column('ad', 'age')
    op.drop_column('ad', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('ad', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ad', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ad', type_='foreignkey')
    op.drop_column('ad', 'category_id')
    op.drop_column('ad', 'price')
    # ### end Alembic commands ###
