"""empty message

Revision ID: b7e4d68f940f
Revises: 571bbec5ca5c
Create Date: 2024-06-07 17:22:40.078717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e4d68f940f'
down_revision: Union[str, None] = '571bbec5ca5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('popular', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad', 'popular')
    # ### end Alembic commands ###
